### ISSUE TITLE
Not working outside of local network

### ISSUE THREAD

**Issue by blair287** [maykar/lovelace-swipe-navigation#43] opened 2020-12-04 14:21 UTC
Used to work on local network and via 4g with domain but now only local network works on HA 118

I get this error when I connect outside my network

Logger: frontend.js.latest.202011112
Source: components/system_log/__init__.py:193
First occurred: 14:13:08 (3 occurrences)
Last logged: 14:18:41

https://*************/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:19:100 Uncaught TypeError: Cannot read property 'shadowRoot' of null

**Comment by KTibow** [comment] 2020-12-04 14:37
Have you tried updating swipe navigation and force refreshing?

**Comment by blair287** [comment] 2020-12-04 22:58
> Have you tried updating kiosk mode and force refreshing?

What's kiosk mode?

**Comment by xekil** [comment] 2020-12-07 17:55
Hello, same problem :(

```
Logger: frontend.js.latest.202011112
Source: components/system_log/__init__.py:193
First occurred: 18:42:13 (2 occurrences)
Last logged: 18:45:38

https://******************/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:19:100 
Uncaught TypeError: Cannot read property 'shadowRoot' of null

```

I saw that there was a similar problem with CCH in 2018 and that the author fixed it :)

https://community.home-assistant.io/t/compact-custom-header/83716/95

Thank you

HA 1.118.5
HASSIO 4.17

**Comment by maykar** [comment] 2020-12-07 22:23
Though I'm sure the errors look similar, the error is pretty generic. It's caused when an element with a shadowroot wasn't found. I believe this to be a duplicate of issue #42 and a conflict with another addon like browser-mod.

Please, try pre-release version 1.3.3. If you use HACS you will need to select "Reinstall" and enable "Show beta versions" and select v1.3.3.

If this is still an issue, be sure that your system is using the correct version by checking that your browser's dev tools console reports version 1.3.3. If it doesn't, clear your cache and/or reinstall. You most likely need to clear the cache of the mobile app as well.

Report back and let me know if this is still an issue or if 1.3.3 solves it. Thank you.

P.S. I am the author of CCH ;)

**Comment by xekil** [comment] 2020-12-08 08:10
Hello, thank you for your answer

I installed version 1.3.3 beta but without success :(

**With the android application, I cleared the cache but it doesn't change anything.**
Error message and it does not work

**With google chrome on Android**
No error message but it doesn't work either

I am using duckdns and this problem only occurs outside of the local network.

Ps: Yes I know you are the author of CCH, it was mainly to help and remind you of the possible solution :)

![sn](https://user-images.githubusercontent.com/69087258/101456889-01bac780-3935-11eb-9eb2-156bc061110e.jpg)

**Comment by xekil** [comment] 2020-12-08 08:22
little info, I restarted HA, I no longer have an error message with the android applciation but it still does not work

**Comment by maykar** [comment] 2021-01-08 16:57
Please, update and try the latest version.

If this is still an issue, be sure that your system is using the correct version by checking that your browser's dev tools console reports the correct version number. If it doesn't, clear your cache and/or reinstall.

Report back and let me know if this is still an issue or if this has been solved. Thank you.

**Comment by xekil** [comment] 2021-01-08 17:04
Hello, I confirm that with the new version it now works correctly.

Thank you so much :)

**Comment by maykar** [comment] 2021-01-08 17:06
Thanks for the follow up, going to close this for now. If this is still an issue for anyone else, don't hesitate to let me know. Thank you!

**Closed as completed by maykar** 2021-01-08 17:06 UTC

**Comment by xekil** [comment] 2021-01-08 17:10
thanks to you for the solution :)
