### ISSUE TITLE
Component error: swipe_nav - Integration 'swipe_nav' not found

### ISSUE THREAD

**Issue by tomeriva** [maykar/lovelace-swipe-navigation#56] opened 2021-06-29 17:07 UTC
Installing version 1.3.5 from HACS, adding
swipe_nav:
  wrap: false
  animate: swipe
  skip_tabs: 5,6,7,8
  prevent_default: true
  swipe_amount: 30

to configuration file, but I get error "Component error: swipe_nav - Integration 'swipe_nav' not found".

![Screenshot from 2021-06-29 20-05-33](https://user-images.githubusercontent.com/62852028/123839160-7b3bf680-d915-11eb-9920-ec2ce5ebc280.png)
![Screenshot from 2021-06-29 20-04-45](https://user-images.githubusercontent.com/62852028/123839165-7bd48d00-d915-11eb-9cf4-9b5533578bcc.png)

**Comment by maykar** [comment] 2021-06-29 17:27
duplicate of #52

This is not an integration/component, it is a lovelace resource

**Closed as completed** 2021-06-30 19:53 UTC
Labels: duplicate
