### ISSUE TITLE
Not working through Nabu casa

### ISSUE THREAD

**Issue by blair287** [maykar/lovelace-swipe-navigation#27] opened 2020-06-14 06:38 UTC
After a reboot swipe is working through Nabu casa but after a day it stops working, works fine whilst local but not via internet.

This error is showing in log.
![Screenshot_20200614-074019__01](https://user-images.githubusercontent.com/44187409/84586855-a6d76600-ae12-11ea-8461-44ef31cb57de.jpg)

**Comment by maykar** [comment] 2020-06-14 22:05
duplicate of #21

**Closed as completed by maykar** 2020-06-14 22:05 UTC
Labels: duplicate
