### ISSUE TITLE
Swipe-navigation doesn't work with HA 0.110 (dev)

### ISSUE THREAD

**Issue by ualex73** [maykar/lovelace-swipe-navigation#23] opened 2020-05-11 07:48 UTC
I am testing with Home Assistant 0.110, which is in development at this moment.

The frontend isn't loading anymore, and i see the following "swipe-navigation" error in my logging:

`2020-05-11 09:42:26 ERROR (MainThread) [frontend.js.latest.202005090] https://hostname/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js?v=1.2.2:10:21 Uncaught TypeError: Cannot read property 'lovelace' of null`

**Comment by iptvcld** [comment] 2020-05-21 03:32
Same Error

Logger: frontend.js.latest.202005190
Source: components/system_log/__init__.py:209
First occurred: 11:18:32 PM (3 occurrences)
Last logged: 11:20:25 PM

https://hostname/local/community/lovelace-swipe-navigation/swipe-navigation.js:10:21 Uncaught TypeError: Cannot read property 'lovelace' of null

**Comment by maykar** [comment] 2020-05-29 22:50
Duplicate of #21

**Closed as completed by maykar** 2020-05-29 22:50 UTC
