### ISSUE TITLE
Only works on default lovelace dashboard

### ISSUE THREAD

**Issue by alekslyse** [maykar/lovelace-swipe-navigation#25] opened 2020-06-11 15:55 UTC
I noticed the swipe only works on the default lovelace dashboard. If I create a second dashboard the swipe does not work, but if I put the second dashboard to the default it works. Would it be possible to enable swipe on all dashboards?

**Comment by maykar** [comment] 2020-06-11 15:58
Duplicate of #21, this project still needs updated to work with the dashboard feature

**Closed as completed by maykar** 2020-06-11 15:58 UTC
Labels: duplicate
